---
title: "procesado_clasificacion"
author: "Antonio Martínez, Julia Palacios, Arturo Pérez, José Enrique Sánchez"
date: "30/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```


```{r lectura datos}
data_9 <- read.csv2('./data/goal_9.csv')
data_9
```

```{r}
country <- 0
year <- 0
goal_9_measure_all_data <- 0
aux <-0

indicator <- '9.2.1'

goal_9 <- data_9 %>%
            filter(stringr::str_detect(Indicator.Name, indicator)) %>%
              distinct(Country.or.Area, .keep_all = TRUE)

country_list <- goal_9$Country.or.Area

# Esto es en el caso de los menores o iguales a 9. Para objetivos posteriores 11,16
goal_9_indicators_as_list <- data_9 %>%
                      distinct(Indicator.Name, .keep_all = TRUE) %>%
                        select(Indicator.Name) %>%
                          map(function(x) substring(x, 11, 15))


goal_9_years_as_list <- data_9 %>%
                      distinct(Year, .keep_all = TRUE) %>%
                        select(Year)

goal_9_measure_as_list <- data_9 %>%
                      distinct(Measure, .keep_all = TRUE) %>%
                        select(Measure)

# for(ind in goal_9_indicators_as_list){
#   goal_9_ind_measures_filtrado <- data_9 %>%
#                                     select(Indicator.Name, Measure) %>%
#                                       filter(stringr::str_detect(Indicator.Name, ind))
# }


headers <- c()
country_value_list <- c()
country_value_list_aux <- c()
for(m in 1:nrow(goal_9_measure_as_list)){
  for (y in 1:nrow(goal_9_years_as_list)) {
    name_column <- paste(goal_9_measure_as_list[m, ], goal_9_years_as_list[y, ], sep="__")
    headers <- c(headers, name_column)
    for (c in country_list) {
       country_value <- data_9 %>%
                        filter(Country.or.Area == c,
                               Measure == goal_9_measure_as_list[m, ],
                               Year == goal_9_years_as_list[y, ]) %>%
                          select(X.Average.Value)
       country_value_list_aux <- c(country_value_list_aux, country_value[1,])
    }
    country_value_list <- c(country_value_list, list(country_value_list_aux))
    country_value_list_aux <- c()
  }
}

# col_numbers_df <- nrow(goal_9_measure_as_list) * nrow(goal_9_years_as_list)

#create data frame with 0 rows and 5 columns
df <- data.frame(matrix(ncol = length(headers), nrow = 0))

#view structure of the data frame
# str(df)

```



```{r}
df <- data.frame(country_value_list)
#provide column names
colnames(df) <- headers
df$country <- country_list
write.csv(df,"data/goal9_measure_year.csv", row.names = TRUE)
```


```{r}
df <- read_delim("data/goal9_measure_year.csv", delim=",")
measures_data <- list()
for (index_measure in 1:nrow(goal_9_measure_as_list)) {

  goal_measure_data <- data_9 %>%
            filter(Measure == goal_9_measure_as_list[index_measure,],
                   !grepl('Americas|Asia|Africa|Oceania|Europe|ODA|America|developing|Developed|countries|Countries|regions|Channel', Country.or.Area)) %>%
  complete(Year) %>%  
  group_by(Country.or.Area,Year) %>% 
  arrange(desc(Year,Country.or.Area)) %>% 
  select(Country.or.Area,Year,X.Average.Value)
  
  names(goal_measure_data)[1] = "Country"
  names(goal_measure_data)[3] = goal_9_measure_as_list[index_measure,]
  
  measures_data <- c(measures_data, goal_measure_data)
  
  if (index_measure == 1) {
    goal_9_measure_all_data <- goal_measure_data
  } else {
    goal_9_measure_all_data<-merge(x=goal_9_measure_all_data,y=goal_measure_data,by=c('Country','Year'),all.x=TRUE)
  }
}
```

```{r}

hdi <- read.csv('./data/HDI.csv', row.names = "country")
hdi_column <- c()
for (row_num in 1:nrow(goal_9_measure_all_data)) {
  row_country <- goal_9_measure_all_data[row_num,"Country"]
  row_year <- paste("X", goal_9_measure_all_data[row_num,"Year"], sep="")
  hdi_value <- hdi[toString(row_country), toString(row_year)]
  hdi_column <- c(hdi_column, hdi_value)
}
```

```{r}
goal_9_measure_all_data$HDI <- hdi_column
hdi_categorical <- c()
for (i in 1:length(hdi_column)) {
  if (is.na(hdi_column[i])) {
    hdi_categorical <- c(hdi_categorical, hdi_column[i])
  } else if(hdi_column[i] < 0.550) {
    hdi_categorical <- c(hdi_categorical, "Bajo")
  } else if (hdi_column[i] < 0.7){
    hdi_categorical <- c(hdi_categorical, "Medio")
  } else if (hdi_column[i] < 0.8) {
    hdi_categorical <- c(hdi_categorical, "Alto")
  } else {
    hdi_categorical <- c(hdi_categorical, "Muy Alto")
  }
}
goal_9_measure_all_data$HDI_categorical <- hdi_categorical
df_hdi <- data.frame(goal_9_measure_all_data)
write.csv(df_hdi,"data/goal_9_measure_all_data.csv", row.names = FALSE)
```


```{r}
library(ggplot2)
library(dplyr)
library(broom)
library(ggpubr)
```

```{r}
df_hdi <- select(df_hdi, -Year)
country.hdi.lm <- lm(HDI ~ Country , data = df_hdi)
summary(country.hdi.lm)
```

```{r}
par(mfrow=c(2,2))
plot(country.hdi.lm)
par(mfrow=c(1,1))
```

```{r}
country.hdi.graph<-ggplot(df_hdi, aes(x=Country, y=HDI))+
                     geom_point()

country.hdi.graph <- country.hdi.graph + geom_smooth(method="lm", col="black")
country.hdi.graph <- country.hdi.graph + stat_regline_equation(label.x = 3, label.y = 7)

country.hdi.graph
```

